name: shopping
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  persistent_bottom_nav_bar_v2: ^4.2.8
  dio: ^5.3.4
  share_plus: ^7.2.1
  awesome_dialog: ^3.1.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  connection_notifier: ^2.0.1
  animated_introduction: ^1.0.4
  flutter_riverpod: ^2.4.8
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  flutter_expanded_tile: ^0.3.7
  riverpod_infinite_scroll: ^1.0.9
  contained_tab_bar_view: ^0.8.0
  flutter_rating_bar: ^4.0.1
  flutter_chat_ui: ^1.6.10
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  open_filex: ^4.3.4
  url_launcher: ^6.2.1
  staggered_grid_view_flutter: ^0.0.4
  line_icons: ^2.0.3
  flutter_swiper_null_safety: ^1.0.2
  expandable: ^5.0.1
  scrollable_positioned_list: ^0.3.8
  get_ip_address: ^0.0.6
  list_picker_dialog_plus: ^0.0.2
  flutter_reorderable_grid_view: ^4.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
     - assets/lang/
     - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
